#!/usr/bin/env ruby

require 'optparse'

mvn = `which mvn`.strip


options = {
  :skip_tests	=> "-Dmaven.test.skip=true",
  :skip_javadoc	=> "-Dmaven.javadoc.skip=true"
}
OptionParser.new do |opts|
	opts.banner = "Usage: #{__FILE__} [options]"

  opts.on "-t", "--tests", "Run tests" do |t|
    options.delete :skip_tests
  end

	opts.on "-j", "--javadoc", "Generate javadoc" do |j|
    options.delete :skip_javadoc
	end
end.parse!

cmd = "#{mvn} clean install #{options.values.join ' '}"

puts
puts "========================================================================="
puts "    #{cmd}"
puts "========================================================================="
puts
puts

IO.popen(cmd) do |io|
	while line = io.gets do puts line end
end
